#%RAML 1.0 DataType
properties:
  id: number
  username: string
  first_name: string
  last_name: string
  salary: number
  designation: string
  DOB: date-only
  Created_at: datetime
  job_type: string
  is_active: boolean