#%RAML 1.0
title: salesforceAccount-sys

/batch:
  get:
    queryParameters:
      data:
        required: false
        type: string
    responses:
      200:
        body:
          application/json:
            type: !include schemas/userType.raml

  post:
    queryParameters:
      fileName:
        required: true
        type: string
    responses:
      202:
        body:
          application/json:
            example: !include examples/getExample.raml    