# This workflow will build a MuleSoft project and deploy to CloudHub

name: Build and Deploy to CloudHub

on:
  push:
    branches: [ main ]
    
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout this repo
      uses: actions/checkout@v3
    - name: Cache dependencies
      uses: actions/cache@v3
      with:
        path: ~/.m2/repository
        key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
        restore-keys: |
          ${{ runner.os }}-maven-
    - name: Set up JDK 1.8
      uses: actions/setup-java@v3
      with:
        distribution: 'zulu'
        java-version: 8
    - name: Build with Maven
      run: mvn -B package --file process-salesforce-account/pom.xml
    - name: Stamp artifact file name with commit hash
      run: |
        cd process-salesforce-account
        artifactName1=$(ls target/*.jar | head -1)
        commitHash=$(git rev-parse --short "$GITHUB_SHA")
        artifactName2=$(ls target/*.jar | head -1 | sed "s/.jar/-$commitHash.jar/g")
        mv $artifactName1 $artifactName2
    - name: Upload artifact 
      uses: actions/upload-artifact@v3
      with:
          name: artifacts
          path: process-salesforce-account/target/*.jar
        
  deploy:
    needs: build
    environment: prod
    runs-on: ubuntu-latest   
    steps:    
    - name: Checkout this repo
      uses: actions/checkout@v3
    - name: Cache dependencies
      uses: actions/cache@v3
      with:
        path: ~/.m2/repository
        key: ${{ runner.os }}-maven-${{ hashFiles('**//pom.xml') }}
        restore-keys: |
          ${{ runner.os }}-maven-
    - uses: actions/download-artifact@v3
      with:
        name: artifacts
    - name: Deploy to CloudHub
      env:
        WORKFLOW_VARIABLE: prod
        USERNAME: ${{ secrets.USERNAME}}
        PASSWORD: ${{ secrets.PASSWORD }}
        CLOUDHUB_APP_NAME: ${WORKFLOW_VARIABLE.CLOUDHUB_APP_NAME}
        REGION: ${WORKFLOW_VARIABLE.REGION}
        RUNTIME: ${WORKFLOW_VARIABLE.RUNTIME}
        ENVIRONMENT: ${WORKFLOW_VARIABLE.ENVIRONMENT}
        WORKERS: ${WORKFLOW_VARIABLE.WORKERS}
        WORKER_TYPE: ${WORKFLOW_VARIABLE.WORKER_TYPE}
        CLIENT_ID: ${{ secrets.CLIENT_ID }}
        CLIENTSECRET:  ${{ secrets.CLIENTSECRET }}
      run: |
        artifactName=$(ls *.jar | head -1)
        mvn deploy -B -X -DmuleDeploy \
        -Dmule.artifact=$artifactName \
        -Danypoint_platform_username="$USERNAME" \
        -Danypoint_platform_password="$PASSWORD" \
        -Denvironment="${ENVIRONMENT}" \
        -Danypoint_platform_client_id="${CLIENT_ID}" \
        -Danypoint_platform_client_secret="${CLIENTSECRET}" \
        -Dcloudhub.application.runtime="${RUNTIME}" \
        -Dcloudhub.application.name="${CLOUDHUB_APP_NAME}" \
        -Dregion="${REGION}" \
        -Dworkers="${WORKERS}" \
        -DworkerType="${WORKER_TYPE}" \
        --file process-salesforce-account/pom.xml
